name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audio_video_progress_bar: ^2.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  objectbox: ^2.5.1
  objectbox_flutter_libs: ^2.5.1
  on_audio_query: ^2.9.0
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  riverpod_annotation: ^2.3.4
  shimmer: ^3.0.0
  text_scroll: ^0.2.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  objectbox_generator: ^2.5.1
  riverpod_generator: ^2.3.11

flutter:
  uses-material-design: true
  
  assets:
  - assets/images/
  - assets/icons/

